// <auto-generated />
using System;
using Gestao_Escala.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestao_Escala.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321193846_AtualizandoModelVigenciaMotorista")]
    partial class AtualizandoModelVigenciaMotorista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestao_Escala.Models.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("FimIntervalo")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraFinal")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("InicioIntervalo")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoJornada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Escala");
                });

            modelBuilder.Entity("Gestao_Escala.Models.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaCnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("VencimentoCnh")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Motorista");
                });

            modelBuilder.Entity("Gestao_Escala.Models.VigenciaEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("VigenciaEscala");
                });

            modelBuilder.Entity("Gestao_Escala.Models.VigenciaMotorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("VigenciaEscalaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VigenciaEscalaId");

                    b.ToTable("VigenciaMotorista");
                });

            modelBuilder.Entity("Gestao_Escala.Models.VigenciaEscala", b =>
                {
                    b.HasOne("Gestao_Escala.Models.Escala", "Escala")
                        .WithMany("Vigencias")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");
                });

            modelBuilder.Entity("Gestao_Escala.Models.VigenciaMotorista", b =>
                {
                    b.HasOne("Gestao_Escala.Models.Motorista", "Motorista")
                        .WithMany("Vigencias")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Escala.Models.VigenciaEscala", "VigenciaEscala")
                        .WithMany("Motoristas")
                        .HasForeignKey("VigenciaEscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorista");

                    b.Navigation("VigenciaEscala");
                });

            modelBuilder.Entity("Gestao_Escala.Models.Escala", b =>
                {
                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("Gestao_Escala.Models.Motorista", b =>
                {
                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("Gestao_Escala.Models.VigenciaEscala", b =>
                {
                    b.Navigation("Motoristas");
                });
#pragma warning restore 612, 618
        }
    }
}
